// <auto-generated />
using System;
using GolfLeagueApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GolfLeagueApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510130000_AddDefaultTeeBoxId")]
    partial class AddDefaultTeeBoxId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GolfLeagueApi.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Golfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalAuthId")
                        .HasColumnType("text")
                        .HasColumnName("external_auth_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_golfers");

                    b.HasIndex("CourseId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_golfers_course_id_email");

                    b.HasIndex("CourseId", "ExternalAuthId")
                        .IsUnique()
                        .HasDatabaseName("ix_golfers_course_id_external_auth_id")
                        .HasFilter("external_auth_id IS NOT NULL");

                    b.ToTable("golfers", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Hole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HandicapIndex")
                        .HasColumnType("integer")
                        .HasColumnName("handicap_index");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Par")
                        .HasColumnType("integer")
                        .HasColumnName("par");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_holes");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_holes_course_id");

                    b.ToTable("holes", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DefaultRoundLength")
                        .HasColumnType("integer")
                        .HasColumnName("default_round_length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_leagues_course_id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.LeagueConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultTeeBoxId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_tee_box_id");

                    b.Property<string>("HandicapSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handicap_system");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<bool>("SubsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("subs_allowed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_league_configurations");

                    b.HasIndex("DefaultTeeBoxId")
                        .HasDatabaseName("ix_league_configurations_default_tee_box_id");

                    b.HasIndex("LeagueId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_configurations_league_id");

                    b.ToTable("league_configurations", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.LeagueMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GolferId")
                        .HasColumnType("uuid")
                        .HasColumnName("golfer_id");

                    b.Property<decimal?>("Handicap")
                        .HasColumnType("numeric")
                        .HasColumnName("handicap");

                    b.Property<bool>("IsCommissioner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commissioner");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_league_memberships");

                    b.HasIndex("GolferId")
                        .HasDatabaseName("ix_league_memberships_golfer_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_league_memberships_season_id");

                    b.ToTable("league_memberships", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_seasons_league_id");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.TeeBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tee_boxes");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_tee_boxes_course_id");

                    b.ToTable("tee_boxes", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_teams_season_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_membership_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_team_memberships");

                    b.HasIndex("LeagueMembershipId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_memberships_league_membership_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_memberships_team_id");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nine")
                        .HasDefaultValue("Front");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasDefaultValue("Regular");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("Id")
                        .HasName("pk_weeks");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_weeks_season_id");

                    b.ToTable("weeks", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Matchup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_a_id");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_b_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_matchups");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_matchups_created_by");

                    b.HasIndex("TeamAId")
                        .HasDatabaseName("ix_matchups_team_a_id");

                    b.HasIndex("TeamBId")
                        .HasDatabaseName("ix_matchups_team_b_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_matchups_updated_by");

                    b.HasIndex("WeekId")
                        .HasDatabaseName("ix_matchups_week_id");

                    b.ToTable("matchups", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Pairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchupId")
                        .HasColumnType("uuid")
                        .HasColumnName("matchup_id");

                    b.Property<TimeOnly?>("TeeTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tee_time");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pairings");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_pairings_created_by");

                    b.HasIndex("MatchupId")
                        .IsUnique()
                        .HasDatabaseName("ix_pairings_matchup_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_pairings_updated_by");

                    b.ToTable("pairings", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.PairingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_membership_id");

                    b.Property<Guid>("PairingId")
                        .HasColumnType("uuid")
                        .HasColumnName("pairing_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pairing_slots");

                    b.HasIndex("LeagueMembershipId")
                        .HasDatabaseName("ix_pairing_slots_league_membership_id");

                    b.HasIndex("PairingId")
                        .HasDatabaseName("ix_pairing_slots_pairing_id");

                    b.ToTable("pairing_slots", (string)null);
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Golfer", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Course", "Course")
                        .WithMany("Golfers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_golfers_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Hole", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Course", "Course")
                        .WithMany("Holes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holes_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.League", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Course", "Course")
                        .WithMany("Leagues")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.LeagueConfiguration", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.TeeBox", "DefaultTeeBox")
                        .WithMany()
                        .HasForeignKey("DefaultTeeBoxId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_league_configurations_tee_boxes_default_tee_box_id");

                    b.HasOne("GolfLeagueApi.Models.League", "League")
                        .WithOne("Configuration")
                        .HasForeignKey("GolfLeagueApi.Models.LeagueConfiguration", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_configurations_leagues_league_id");

                    b.Navigation("DefaultTeeBox");

                    b.Navigation("League");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.LeagueMembership", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Golfer", "Golfer")
                        .WithMany("Memberships")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_memberships_golfers_golfer_id");

                    b.HasOne("GolfLeagueApi.Models.Season", "Season")
                        .WithMany("Memberships")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_memberships_seasons_season_id");

                    b.Navigation("Golfer");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Season", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.TeeBox", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Course", "Course")
                        .WithMany("TeeBoxes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tee_boxes_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Team", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Season", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.TeamMembership", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", "LeagueMembership")
                        .WithOne("TeamMembership")
                        .HasForeignKey("GolfLeagueApi.Models.TeamMembership", "LeagueMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_league_memberships_league_membership_id");

                    b.HasOne("GolfLeagueApi.Models.Team", "Team")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_teams_team_id");

                    b.Navigation("LeagueMembership");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Matchup", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matchups_league_memberships_created_by");

                    b.HasOne("GolfLeagueApi.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchups_teams_team_a_id");

                    b.HasOne("GolfLeagueApi.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchups_teams_team_b_id");

                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matchups_league_memberships_updated_by");

                    b.HasOne("GolfLeagueApi.Models.Week", "Week")
                        .WithMany("Matchups")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchups_weeks_week_id");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Pairing", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pairings_league_memberships_created_by");

                    b.HasOne("GolfLeagueApi.Models.Matchup", "Matchup")
                        .WithOne("Pairing")
                        .HasForeignKey("GolfLeagueApi.Models.Pairing", "MatchupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pairings_matchups_matchup_id");

                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pairings_league_memberships_updated_by");

                    b.Navigation("Matchup");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.PairingSlot", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.LeagueMembership", "LeagueMembership")
                        .WithMany()
                        .HasForeignKey("LeagueMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pairing_slots_league_memberships_league_membership_id");

                    b.HasOne("GolfLeagueApi.Models.Pairing", "Pairing")
                        .WithMany("PairingSlots")
                        .HasForeignKey("PairingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pairing_slots_pairings_pairing_id");

                    b.Navigation("LeagueMembership");

                    b.Navigation("Pairing");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Week", b =>
                {
                    b.HasOne("GolfLeagueApi.Models.Season", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_weeks_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Course", b =>
                {
                    b.Navigation("Golfers");

                    b.Navigation("Holes");

                    b.Navigation("Leagues");

                    b.Navigation("TeeBoxes");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Golfer", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.League", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.LeagueMembership", b =>
                {
                    b.Navigation("TeamMembership");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Matchup", b =>
                {
                    b.Navigation("Pairing");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Pairing", b =>
                {
                    b.Navigation("PairingSlots");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Season", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Teams");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Team", b =>
                {
                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("GolfLeagueApi.Models.Week", b =>
                {
                    b.Navigation("Matchups");
                });
#pragma warning restore 612, 618
        }
    }
}
